name			    = "mos6502_create_nop"
description		    = "Create NOP ROM"
long-description	    = """This is a tool to create a rom image with NOP commands.

This program can be used to create a ROM immage for the MOS 6502 tutorial from Ben Eater.

Development versions available with:

```sh
alr index --add "git+https://github.com/krischik/alire-index.git#develop" --name krischik
``` 

Source code and testsuite available on [SourceForge](https://git.code.sf.net/p/tutorial-6502/git)
"""
version			    = "1.5.3"
licenses		    = "GPL-3.0-or-later"
authors			    = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers		    = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins	    = ["krischik"]
executables		    = ["create_nop"]
website			    = "https://sourceforge.net/projects/tutorial-6502"
tags			    = ["mos-6502", "tools", "retrocomputing", "ada2022"]

[build-switches]
"*".ada_version		    = "Ada2022"
"*".source_encoding	    = "UTF_8"
development.compile_checks  = "Warnings"
development.contracts	    = "Yes"
development.debug_info	    = "Yes"
development.optimization    = "Debug"
development.runtime_checks  = "Overflow"
release.compile_checks	    = "Warnings"
release.contracts	    = "No"
release.debug_info	    = "No"
release.optimization	    = "Performance"
release.runtime_checks	    = "Default"
validation.compile_checks   = "Warnings"
validation.contracts	    = "Yes"
validation.debug_info	    = "Yes"
validation.optimization     = "Debug"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl_desktop		    = "^8.0"

[[actions]]
type			    = "test"
command			    = ["alr", "test"]
directory		    = "test"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=syntax :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:04d4b36902fc636356bd5708b1262177b0f52fcbaf30f76441be15ce381a57f4",
"sha512:a92f2d1a747f0745dc59657692ef26316d3bee63485760f26ca6bb576d586f74fde632a684058419a94cbcbc2594e169c23ec69059530d85b07b1cb1d0089972",
]
url = "https://sourceforge.net/projects/tutorial-6502/files/Alire/mos6502_create_nop-1.5.3.tgz"

