name			    = "mos6502_create_led"
description		    = "Create ROM with little program"
long-description	    = """This is a tool to create a rom image with little program.

This program can be used to create a ROM immage for the MOS 6502 tutorial from Ben Eater.

Development versions available with:

```sh
alr index --add "git+https://github.com/krischik/alire-index.git#develop" --name krischik
```

Source code and testsuite available on [SourceForge](https://git.code.sf.net/p/tutorial-6502/git)
"""
version			    = "1.5.3"
licenses		    = "GPL-3.0-or-later"
authors			    = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers		    = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins	    = ["krischik"]
executables		    = ["create_led"]
website			    = "https://sourceforge.net/projects/tutorial-6502"
tags			    = ["mos-6502", "tools", "retrocomputing", "ada2022"]

[build-switches]
"*".ada_version		    = "Ada2022"
"*".source_encoding	    = "UTF_8"
development.compile_checks  = "Warnings"
development.contracts	    = "Yes"
development.debug_info	    = "Yes"
development.optimization    = "Debug"
development.runtime_checks  = "Overflow"
release.compile_checks	    = "Warnings"
release.contracts	    = "No"
release.debug_info	    = "No"
release.optimization	    = "Performance"
release.runtime_checks	    = "Default"
validation.compile_checks   = "Warnings"
validation.contracts	    = "Yes"
validation.debug_info	    = "Yes"
validation.optimization     = "Debug"
validation.runtime_checks   = "Everything"

[[depends-on]]
adacl_desktop		    = "^8.0"

[[actions]]
type			    = "test"
command			    = ["alr", "test"]
directory		    = "test"

# vim: set textwidth=0 nowrap tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=syntax :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:ff29ad3f7cdca06d6cc3ec2fcfb5bf2477d1022be57a4a746b1b6d1cb4dd677c",
"sha512:51ce47bad326f590a3bf172709a84eb67bc1515b06a25843e867713d25577d8e4c7df984e78236e40a2199f7a21b32314f6cc915a561d0f6f1be522881aa056d",
]
url = "https://sourceforge.net/projects/tutorial-6502/files/Alire/mos6502_create_led-1.5.3.tgz"

