name					= "pico_ada_c08_serial_communication"
description				= "Chapter 8: Serial Communication (UART, USB, SWD)"
long-description			= """Learn three different ways to perform serial communication with the
Raspberry Pi Pico using Ada - SWD semihosting, UART and USB CDC-ACM.

Three practical serial output methods together with complete example programs for sending and receiving data.

Contained in Chapter 08 are:

1. sketch_08_1_serial_print.adb	- Chapter 8.1 Print on all three destinations
2. sketch_08_2_serial_rw.adb	- Chapter 8.2 Read data from all three destinations

Read the full tutorial at [Chapter 8: Serial Communication (UART, USB,
SWD)](https://pi-ada-tutorial.sourceforge.io/pico_ada_c08_serial_communication), [GNATdoc
documentation](https://pi-ada-tutorial.sourceforge.io/gnatdoc/pico_doc/), [SourceForge
repository](https://sourceforge.net/p/pi-ada-tutorial/code/ci/master/tree/pico_ada_c08_serial_communication/)
"""
version					= "1.8.0"
licenses				= "GPL-3.0-or-later"
authors					= ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers				= ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins			= ["krischik"]
website					= "https://pi-ada-tutorial.sourceforge.io/pico_ada_c08_serial_communication"
tags					= ["raspberry", "pi", "pico", "rp2040", "tasking", "light-tasking", "ada2022", "embedded"]
executables				= [
    "sketch_08_1_serial_print",
    "sketch_08_2_serial_rw"]

[build-switches]
"*".ada_version				= ["-gnat2022"]
development.compile_checks		= "Warnings"
development.contracts			= "Yes"
development.runtime_checks		= "Overflow"
release.compile_checks			= "Warnings"
release.contracts			= "No"
release.runtime_checks			= "Default"
validation.compile_checks		= "Warnings"
validation.contracts			= "Yes"
validation.runtime_checks		= "Everything"

[[depends-on]]
embedded_rp2040				= "^15.4"
pico_bsp				= "^2.2"
pico_xbsp				= "^1.8"
rp2040_hal				= "^2.7.1"

[configuration.values]
adacl_embedded.Event_Log_Buffer_Size	= 0
adacl_embedded.Variant			= "no_tasking"
embedded_rp2040.Board			= "rpi_pico"
embedded_rp2040.Max_CPUs		= 2
pico_xbsp.Variant			= "tasking"
rp2040_hal.Interrupts			= "bb_runtimes"
rp2040_hal.Use_Startup			= false

# vim: set textwidth=120 nowrap tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab :
# vim: set filetype=toml fileencoding=latin1 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:149abc1746c734cc7e4024e6358eef2c4730ba9b22333ef5345775250862d263",
"sha512:8fcb433e6ee3ff0d55f8bc746d6d7a515f1e476d05523e3a61144fa72de16962181034c421281a6324b2b7f67eb39e348d8ac71dbafc0390fc0421c8ff63cbf0",
]
url = "https://sourceforge.net/projects/pi-ada-tutorial/files/Alire/pico_ada_c08_serial_communication-1.8.0.tgz"

