name = "amqp"
version = "0.3.0"
description = "AMQP 0-9-1 client library for Ada"
website = "https://github.com/geewiz/amqp_ada"
authors = ["Jochen Lillich"]
maintainers = ["contact@geewiz.dev"]
maintainers-logins = ["geewiz"]
licenses = "Apache-2.0"
tags = ["amqp", "messaging", "rabbitmq", "protocol"]

project-files = ["amqp.gpr"]

[gpr-externals]

[gpr-set-externals]

[available.'case(os)']
linux = true
macos = true
windows = true

[origin]
commit = "7d11f7fb97d116baf60707d973e7646ba2bda4e0"
url = "git+https://github.com/geewiz/amqp_ada.git"

