name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "25.0.0"
tags = ["unicode", "json", "text", "xml", "template"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0 WITH LLVM-exception"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr", "gnat/vss_regexp.gpr", "gnat/vss_xml.gpr", "gnat/vss_xml_templates.gpr"]

[[depends-on]]
gnat = ">=11 & <2000" # Uses Ada 2022 syntax

[configuration]
disabled = true

[origin]
archive-name = "vss-25.0.0.tar.gz"
url = "https://github.com/adacore/VSS-archived/archive/refs/tags/v25.0.0.tar.gz"
hashes = ["sha512:d32b3f5213f3909423633380743824a020bb0d6ef1f0157fa223c3a38110bc161b9739c3bf0b4c82c202d832b86e9e429eabcfd019505cc215785ca2b08e24bc"]
