name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "23.0.0"
tags = ["unicode", "json", "text", "xml", "template"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "Apache-2.0"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr", "gnat/vss_regexp.gpr", "gnat/vss_xml.gpr", "gnat/vss_xml_templates.gpr"]

[configuration]
disabled = true

[origin]
archive-name = "vss-23.0.0.tar.gz"
url = "https://github.com/AdaCore/VSS-archived/archive/refs/tags/v23.0.0.tar.gz"
hashes = ["sha512:8bc153826ac40ea014141ae43ec7939c6cd2da51cafe9841f9b582a877a3b5b4177d7a469684d409dac93f4a470a9c88f38e44eb186af9361b0fef5ceb3ec8de"]

[[depends-on]]
gnat = ">=12 & <13.3.0"
