name = "vss"
description = "Advanced string and text manipulation with Unicode support"
version = "22.0.0"
tags = ["unicode", "json", "text"]

authors = ["AdaCore"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
website = "https://github.com/AdaCore/VSS"

project-files = ["gnat/vss_text.gpr", "gnat/vss_json.gpr"]

[origin]
archive-name = "vss-22.0.0.tar.gz"
url = "https://github.com/AdaCore/VSS-archived/archive/refs/tags/v22.0.0.tar.gz"
hashes = ["sha512:d1887c2bb3862c4b005dfca32e63e1a7f5532f713f77b7e5e9db56fb6d61552e1e469115c8b1d1f4711a06d256acdb8837c62a627d14917d2a12de811c2336e4"]

[[depends-on]]
gnat = ">=2020|(>=11 & <=2000)"
