name = "swan_ada"
description = "Stuff We All Need - utilities collection for ada"
version = "0.1.0"

authors = ["Matheus Xavier"]
maintainers = ["Matheus Xavier <mxavierdev@gmail.com>"]
maintainers-logins = ["xadaemon"]
licenses = "Apache-2.0"
website = "https://github.com/xadaemon/swan_ada"
tags = []

[origin]
commit = "3bba2f4c6154ef939a610cd61230fe5edd5484d8"
url = "git+https://github.com/xadaemon/swan_ada.git"

