name = "mavlink_ardupilotmega_v2"
description = "MAVLink, ardupilotmega dialect"
version = "1.0.0"

authors = ["Fil Andrii", "Max Reznik"]
maintainers = ["Fil Andrii <root.fi36@gmail.com>", "Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["python36", "reznikmm"]

licenses = "MIT"
website = "https://github.com/reznikmm/mavlink_ardupilotmega"
tags = ["embedded", "network", "drone"]

project-files = ["gnat/mavlink_ardupilotmega_v2.gpr"]

[build-switches]
"*".style_checks = ["-gnatyN"]
"*".ada_version = "Ada2022"

[[depends-on]]
mavlink_common_v2 = "^1.0.0"


[origin]
commit = "2c1ea302ce05b9360a2f7e9b9fc12753d8497199"
url = "git+https://github.com/reznikmm/mavlink_ardupilotmega.git"

