name = "backoff_ada"
version = "0.1.0"
description = "Exponential backoff with jitter and retry for Ada"
website = "https://github.com/kokhlo/backoff-ada"
authors = ["Konstantin Khlopkov"]
maintainers = ["kokhlo <konstantin.khlopkov93@gmail.com>"]
maintainers-logins = ["kokhlo"]
licenses = "MIT"
tags = ["backoff", "retry", "jitter", "exponential"]

[origin]
url = "https://github.com/kokhlo/backoff-ada/archive/refs/tags/v0.1.0.tar.gz"
hashes = [
"sha512:2a7d366ab96ce025fcf1d619ff08544bf745528bbfc6fe0ce794317176643d7a24d56083c958f475bcc70b044e888ad019ad6ebdfbf328f6a8d6a75e926a60f1"
]