description = "Utility for directing compilation"
name = "make"

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"

origin.'case(os)'.freebsd = ["gmake"]
origin.'case(os)'.'...' = ['make']

[[external]]
kind = "version-output"
version-regexp = ".*Make ([\\d\\.]+).*"
version-command = [ "gmake", "--version" ]
