name                        = "pico_ada_c01_blink"
description                 = "Chapter 1: Blinking LEDs"
long-description            = """Getting Started with Ada on the Raspberry Pi Pico
This create implement the samples of Chapter 1 of the
[Freenove Kit for Raspberry Pi Pico C Tutorial](https://docs.freenove.com/projects/fnk0058/en/latest/fnk0058/codes/C.html)

Contained in Chapter 01 are:

1. blink - Jeremy Grosser Ada sample 
2. - Chapter 1.1 Blink internal LED
3. - Chapter 1.2 Blink external LED

Read the full tutorial at [Chapter 1: Blinking LEDs - Getting Started with Ada
on the Raspberry Pi
Pico](https://pi-ada-tutorial.sourceforge.io/pico_ada_c01_blink)

> Starting simple with LED blinking in Ada - internal LED, external LED with
> proper renaming, and a look at why Ravenscar looks so clean (even if it's not
> quite ready for everyday use yet).

GNATdoc documentation:
https://pi-ada-tutorial.sourceforge.io/gnatdoc/pico_ada_c01_blink/

SourceForge repository:
https://sourceforge.net/projects/pi-ada-tutorial/
"""

version                     = "1.3.1"
licenses                    = "GPL-3.0-or-later"
authors                     = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers                 = ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins          = ["krischik"]
website                     = "https://pi-ada-tutorial.sourceforge.io/pico_ada_c01_blink"
tags                        = ["raspberry", "pi", "pico", "rp2040", "ada2022", "embedded"]
executables                 = [
    "blink",
    "sketch_01_1_blink",
    "sketch_01_2_blink"
]

[build-switches]
"*".ada_version             = ["-gnat2022"]
development.compile_checks  = "Warnings"
development.contracts       = "Yes"
development.runtime_checks  = "Overflow"
release.compile_checks      = "Warnings"
release.contracts           = "No"
release.runtime_checks      = "Default"
validation.compile_checks   = "Warnings"
validation.contracts        = "Yes"
validation.runtime_checks   = "Everything"

[[depends-on]]
pico_bsp                    = "^2"

# vim: set textwidth=72 nowrap tabstop=8 shiftwidth=4 softtabstop=4 expandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:f9bf7d9678d18e01044f1d42d9717e4587169bad3f88a3a4df859ea860273ba3",
"sha512:a36cdfcc83e35de9e7a178fa24e921443dffbc4b0456f7f2d1038caf1f5941a6bfd48b2ebd150ca1226243865e2fea0829e7542337b1373f17d67a53afd7c286",
]
url = "https://sourceforge.net/projects/pi-ada-tutorial/files/Alire/pico_ada_c01_blink-1.3.1.tgz"

