description = "SQLite3 is an SQL database engine in a C library."
name = "sqlite3"

maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["sqlite3"]
fedora = ["sqlite"]
