name = "rabbitmq"
description = "Ada bindings for the librabbitmq C client library"
version = "0.1.0"

authors = ["Jochen Lillich"]
maintainers = ["Jochen Lillich <hello@geewiz.dev>"]
maintainers-logins = ["geewiz"]
licenses = "MIT"
website = "https://github.com/geewiz/rabbitmq_ada"
tags = ["rabbitmq", "amqp", "message", "queue"]

[origin]
commit = "4db66681a7e457e0d358088a7c425869f29bc89d"
url = "git+https://github.com/geewiz/rabbitmq_ada.git"
