name = "rabbitmq"
description = "Ada bindings for the librabbitmq C client library"
version = "0.1.0"

authors = ["Jochen Lillich"]
maintainers = ["Jochen Lillich <hello@geewiz.dev>"]
maintainers-logins = ["geewiz"]
licenses = "MIT"
website = "https://github.com/geewiz/rabbitmq_ada"
tags = ["rabbitmq", "amqp", "message", "queue"]

[origin]
commit = "a058588a5a89445fd52686753017f27f0b8a49cf"
url = "git+https://github.com/geewiz/rabbitmq_ada.git"
