name        = "lace_shared"
description = "Default settings for GPR files in the Lace project."
version     = "1.0.0"

authors            = ["Rod Kay"]
maintainers        = ["Rod Kay <rodakay5@gmail.com>"]
maintainers-logins = ["charlie5"]

licenses = "ISC"
website  = "https://github.com/charlie5/lace"

[origin]
commit = "934d277661e0ed8bdc2013f9fe24ac00c99a544c"
subdir = "./0-floor/lace_shared/"
url = "git+https://github.com/charlie5/lace.git"

