name = "light_tasking_nrf52832"
description = "light-tasking runtime for the NRF52832 SoC"
version = "15.2.0"

long-description = """
## Usage

First edit your `alire.toml` file and add the following elements:
 - Add `light_tasking_nrf52832` in the dependency list:
   ```toml
   [[depends-on]]
   light_tasking_nrf52832 = "*"
   ```

Then edit your project file to add the following elements:
 - "with" the run-time project file. With this, gprbuild will compile the run-time before your application
   ```ada
   with "$(runtime_proj_prefix)_build.gpr";
   ```
 - Specify the `Target` and `Runtime` attributes:
   ```ada
      for Target use $(runtime_proj_prefix)_build'Target;
      for Runtime ("Ada") use $(runtime_proj_prefix)_build'Runtime ("Ada");
   ```
"""

authors = ["AdaCore", "Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
tags = ["embedded", "runtime"]
website = "https://github.com/damaki/community-bb-runtimes"

project-files = ['runtime_build.gpr', 'ravenscar_build.gpr']

[configuration]
generate_gpr = false
generate_c = false
output_dir = "gnat_user"

[configuration.variables]
Time_Base = { type = "Enum", values = ["RTC0", "RTC1", "RTC2"], default = "RTC2" }
LFCLK_Src = { type = "Enum", values = ["Xtal", "RC", "Synth"], default = "Xtal" }
Use_SWO_Trace = { type = "Boolean", default = true }
Use_Reset_Pin = { type = "Boolean", default = true }

[[depends-on]]
gnat_arm_elf = "^15"

[origin]
hashes = [
"sha256:8c6f47852949d6a4eff065ead9d1ec347ab9ec2463be94abd911d1f5ae9a1650",
"sha512:2706a9fc6e3596aec1d58183ab69a28f68febb02beb11afaedb62d84d64b68d0cb16a406b42feee9ff21254ae008a0463153a4b4d2b590b0f74b4a8417bbca46",
]
url = "https://github.com/damaki/community-bb-runtimes/releases/download/v15.2.0/light-tasking-nrf52832-15.2.0.tar.gz"

