name = "zblib"
description = "Library for ZanyBlue Ada Localization"
version = "1.5.0"

authors = ["Michael Rohan"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
licenses = "custom-zanyblue"
website = "https://sourceforge.net/projects/zanyblue"
tags = ["localization", "l10n", "international", "i18n"]

project-files = ["src/zanyblue.gpr"]

[origin]
commit = "e4848ca7663e3cf37ee76a5ecfade082d54afeb7"
url = "git+https://github.com/Blady-Com/zanyblue.git"

