name = "opencv_geometry"
description = "Thick Ada binding to OpenCV Geometry"
version = "0.2.0"

authors = ["Zack Boll"]
maintainers = ["Zack Boll <zackboll@gmail.com>"]
maintainers-logins = ["zackboll"]
licenses = "Apache-2.0"
website = "https://github.com/zackboll/opencv_geometry_ada"
tags = ["opencv", "computer-vision", "binding", "ada"]

[[depends-on]]
opencv_core = ">=0.2.0 & <0.4.0"

[[depends-on]]
opencv = "*"

[[depends-on]]
pkg_config = "*"

[depends-on.'case(os)'.windows]
mingw_w64_gcc = "*"

[environment.'case(distribution)']
msys2 = { PATH.prepend = "${CRATE_ROOT}/lib" }

[[actions]]
type = "pre-build"
command = ["sh", "scripts/configure_opencv.sh"]

[[actions]]
type = "test"
directory = "tests"
command = ["alr", "run"]

[origin]
commit = "42afa67a2f7c42c04612d3a019e5fdd029cea257"
url = "git+https://github.com/zackboll/opencv_geometry_ada.git"
