name = "oherr"
description = "A Rust-style Result type for Ada (oh, error!)."
version = "0.1.0"

authors = ["0xA672"]
maintainers = ["0xA672 <Cero0xA672@outlook.com>"]
licenses = "MIT OR Apache-2.0"
website = "https://github.com/0xA672/oherr"
tags = ["result", "error-handling", "functional", "rust", "option"]
maintainers-logins = ["0xA672"]

[origin]
commit = "5da8ddd4ac52c12b0d89712f8ad3023576fc667a"
url = "git+https://github.com/0xA672/oherr.git"

