name = "swan"
description = "Stuff We All Need - utilities collection for ada"
version = "0.2.0"

authors = ["Matheus Xavier"]
maintainers = ["Matheus Xavier <mxavierdev@gmail.com>"]
maintainers-logins = ["xadaemon"]
licenses = "Apache-2.0"
website = "https://github.com/xadaemon/swan_ada"
tags = ["utilities", "buffers", "collections"]

[origin]
commit = "ac56e19874c4cfa4890d727fa8c55d05f6c039dc"
url = "git+https://github.com/xadaemon/swan_ada.git"

