name = "atomic"
description = "Standalone Ada/SPARK bindings to GCC atomic built-ins"
version = "1.1.0"

licenses = "MIT"
authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
website = "https://github.com/Fabien-Chouteau/atomic"
tags = ["atomic", "spark", "embedded", "nostd"]

[configuration.variables]
Backend = {type = "Enum",  values = ["Intrinsic", "armv6m", "rp2040_spinlock"], default = "Intrinsic"}
RP2040_Spinlock_ID = {type = "Integer",  first = 0, last = 31, default = 31 }

[origin]
commit = "5e6250a055565914cd614f38855b0cb14620b889"
url = "git+https://github.com/Fabien-Chouteau/atomic"

