name = "light_tasking_nrf52840"
description = "light-tasking runtime for the nRF52840 SoC"
version = "14.1.1"

long-description = """
## Usage

First edit your `alire.toml` file and add the following elements:
 - Add `light_tasking_nrf52840` in the dependency list:
   ```toml
   [[depends-on]]
   light_tasking_nrf52840 = "*"
   ```

Then edit your project file to add the following elements:
 - "with" the run-time project file. With this, gprbuild will compile the run-time before your application
   ```ada
   with "ravenscar_build.gpr";
   ```
 - Specify the `Target` and `Runtime` attributes:
   ```ada
      for Target use ravenscar_build'Target;
      for Runtime ("Ada") use ravenscar_build'Runtime ("Ada");
   ```
"""

authors = ["AdaCore", "Daniel King"]
maintainers = ["Daniel King <damaki.gh@gmail.com>"]
maintainers-logins = ["damaki"]
licenses = "GPL-3.0-or-later WITH GCC-exception-3.1"
tags = ["embedded", "runtime"]
website = "https://github.com/damaki/nrf52-runtimes"

project-files = ['runtime_build.gpr', 'ravenscar_build.gpr']

[configuration]
generate_gpr = false
generate_c = false
output_dir = "gnat_user"

[configuration.variables]
Time_Base = { type = "Enum", values = ["RTC0", "RTC1", "RTC2"], default = "RTC2" }
LFCLK_Src = { type = "Enum", values = ["Xtal", "RC", "Synth"], default = "Xtal" }
Use_SWO_Trace = { type = "Boolean", default = true }
Use_Reset_Pin = { type = "Boolean", default = true }

[[depends-on]]
gnat_arm_elf = "^14"

[origin]
hashes = [
"sha256:11584e0b849ea621c393072f69a74f80906ede4d6815eecd5f87e11d9ffdf272",
"sha512:7cda877ed9f81b66da64f04f2b8c860d1e42a42a79b420b1fb830ea0a42ad39064447a8a1f20a935806574e68649c08ca10ad1dbac20b90e426b1142223a681b",
]
url = "https://github.com/damaki/nrf52-runtimes/releases/download/v14.1.1/light-tasking-nrf52840-14.1.1.tar.gz"

