name				= "pico_ada_c01_blink_e"
description			= "Chapter 1 Reloaded: Blinking LEDs on Both Cores"
long-description		= """Blinking LEDs on Both Cores Updated Chapter 1 using the new embedded_rp2040
runtime - now with proper multi-core support, Ada.Real_Time, and delay until for accurate, slippage-free LED blinking on
Raspberry Pi Pico.

After quick community help, I rewrote Chapter 1 to use light tasking on both RP2040 cores. No more manual timers -
clean, precise dual-LED blinking with zero slippage.

Contained in Chapter 01 reloaded are:

1. blink	     - Jeremy Grosser Ada sample
2. sketch_01_1_blink - Chapter 1.1 Blink internal LED
3. sketch_01_2_blink - Chapter 1.2 Blink external LED
4. double_blink-main - double blink using both cores.

Read the full tutorial at [Chapter 1 Reloaded: Dual-Core Light Tasking - Blinking LEDs on Both
Cores](https://pi-ada-tutorial.sourceforge.io/pico_ada_c01_blink_e), [GNATdoc
documentation](https://pi-ada-tutorial.sourceforge.io/gnatdoc/pico_ada_c01_blink_e/), [SourceForge
repository](https://sourceforge.net/p/pi-ada-tutorial/code/ci/master/tree/pico2_ada_c01_blink_lt/)
"""

version				= "1.7.0"
licenses			= "GPL-3.0-or-later"
authors				= ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers			= ["Martin Krischik <krischik@users.sourceforge.net>"]
maintainers-logins		= ["krischik"]
website				= "https://pi-ada-tutorial.sourceforge.io/pico_ada_c01_blink_e"
tags				= ["raspberry", "pi", "pico", "rp2040", "tasking", "light-tasking", "ada2022", "embedded"]
executables			= [
    "blink",
    "double_blink-main",
    "sketch_01_1_blink",
    "sketch_01_2_blink",
    "uart_echo"
]

[build-switches]
"*".ada_version			= ["-gnat2022"]
development.compile_checks	= "Warnings"
development.contracts		= "Yes"
development.runtime_checks	= "Overflow"
release.compile_checks		= "Warnings"
release.contracts		= "No"
release.runtime_checks		= "Default"
validation.compile_checks	= "Warnings"
validation.contracts		= "Yes"
validation.runtime_checks	= "Everything"

[[depends-on]]
rp2040_hal			= "^2.7.1"
pico_bsp			= "^2.2"
pico_xbsp			= "^1.7"
embedded_rp2040			= "^15.4"

[configuration.values]
rp2040_hal.Use_Startup		= false
rp2040_hal.Interrupts		= "bb_runtimes"
embedded_rp2040.Max_CPUs	= 2
embedded_rp2040.Board		= "rpi_pico"

# vim: set textwidth=120 nowrap tabstop=8 shiftwidth=4 softtabstop=4 noexpandtab :
# vim: set filetype=toml fileencoding=utf-8 fileformat=unix foldmethod=diff :
# vim: set spell spelllang=en_gb :

[origin]
hashes = [
"sha256:661b9c20483d47fa9d061fc41df6de5a119edba085203ece98d0b5a07c3f5cfa",
"sha512:eacfdfc2a2c2f2c5dfffbe3009d80d663569c74121a6f0a0c0a26f34b85aa6a61d22fb554a014fdef9dfcbce72796b7214abcc905d7131a963008411e31859ec",
]
url = "https://sourceforge.net/projects/pi-ada-tutorial/files/Alire/pico_ada_c01_blink_e-1.7.0.tgz"

