name = "snowflake"
version = "0.1.0"
description = "Twitter Snowflake distributed ID generator"
website = "https://github.com/kokhlo/snowflake-ada"
authors = ["Konstantin Khlopkov"]
maintainers = ["kokhlo <konstantin.khlopkov93@gmail.com>"]
maintainers-logins = ["kokhlo"]
licenses = "MIT"
tags = ["snowflake", "networking"]

[origin]
url = "https://github.com/kokhlo/snowflake-ada/archive/refs/tags/v0.1.0.tar.gz"
hashes = [
"sha512:261d3892d4efda14d8e0875164631c33a563ff19c44cb41180212062737b0453b11cc109f813709bd5c1f403556e448d0757dda697424ce62cefe9baf1fb71e9"
]
