name = "websocket"
version = "0.2.1"
description = "RFC 6455 WebSocket client: framing and handshake"
website = "https://github.com/kokhlo/websocket-ada"
authors = ["Konstantin Khlopkov"]
maintainers = ["kokhlo <konstantin.khlopkov93@gmail.com>"]
maintainers-logins = ["kokhlo"]
licenses = "MIT"
tags = ["websocket", "networking"]

project-files = ["websocket_ada.gpr"]

[origin]
commit = "a9c412e61047421405c5a92ca7629777943bd5ce"
url = "git+https://github.com/kokhlo/websocket-ada.git"
