name = "tzif"
description = "Parsing and querying of IANA's compiled timezone information"
version = "1.0.0-rc1"
authors = ["Michael Gardner"]
maintainers = ["Michael Gardner <mike@abitofhelp.com>"]
maintainers-logins = ["abitofhelp"]
licenses = "BSD-3-Clause"
website = "https://github.com/abitofhelp/tzif_ada.git"
project-files = ["tzif.gpr"]
tags = [
    "timezone",
    "zoneinfo",
    "tzif",
    "tzdata",
    "iana",
    "time",
    "rfc9636",
    "parser",
    "functional",
    "result-monad",
]

[build-switches]
"*".Ada_Version = "Ada2022"
"*".Style_Checks = "yes"

[[depends-on]]

[gpr-externals]
TZIF_BUILD_MODE = ["dev", "release"]

[gpr-set-externals]
TZIF_BUILD_MODE = "dev"

[environment]

[[depends-on]]
gnatcoll = "^25.0.0"

[[depends-on]]
functional = "^2.0.0"

[origin]
commit = "566cd0bf9eb735bcc96c399c0fc17841af682a8c"
url = "git+https://github.com/abitofhelp/tzif_ada.git"

