name = "tzif"
description = "Parsing and querying of IANA's Timezone Information File Library (tzif)"
version = "3.0.0"
authors = ["Michael Gardner"]
maintainers = ["Michael Gardner <mike@abitofhelp.com>"]
maintainers-logins = ["abitofhelp"]
licenses = "BSD-3-Clause"
website = "https://github.com/abitofhelp/tzif"
project-files = ["tzif.gpr"]
tags = [
    "timezone",
    "zoneinfo",
    "tzif",
    "tzdata",
    "iana",
    "time",
    "rfc9636",
    "parser",
    "functional",
    "result-monad",
]

[build-switches]
"*".Ada_Version = "Ada2022"
"*".Style_Checks = "yes"

[[depends-on]]
gnat = ">=13"

[[depends-on]]
gnatcoll = "^25.0.0"

[[depends-on]]
functional = "^4.0.0"


[origin]
commit = "712316c14a02556c4e071fcfe1437709a63b88a2"
url = "git+https://github.com/abitofhelp/tzif_ada.git"

