name = "jintp"
description = "Template parser in Ada based on Jinja2"
version = "1.0.1"

authors = ["Rene Hartmann"]
maintainers = ["Rene Hartmann <rhartmann@users.sourceforge.net>"]
maintainers-logins = ["rehartmann"]
licenses = "BSD-2-Clause"
website = "https://github.com/rehartmann/JinTP"
tags = ["templates", "jinja", "jinja2"]

[origin]
commit = "732a46b2fba56e7e99d502fa2b7e3bba522b213f"
url = "git+https://github.com/rehartmann/JinTP.git"

