name = "espidf_event"
version = "0.1.0"
website = "https://github.com/godunko/espidf_event"
description = "Ada/ESP-IDF: Event Loop Library bindings"
long-description = """
Ada bindings for the ESP-IDF Event Loop Library (`esp_event`).

Covers creation of the default event loop and registration/unregistration of event handlers,
as needed by other components (Wi-Fi, network interfaces) to report asynchronous events.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "esp", "esp32", "espidf", "event"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
espidf = "^0.2.0"

[origin]
commit = "210b46d83d8d41d26cfdf4cb005130aed1ec9bf2"
url = "git+https://github.com/godunko/espidf_event.git"

