name = "den"
description = "Directory Enumeration Softlink Aware"
version = "0.1.0"

authors = ["Alejandro R. Mosteo"]
maintainers = ["Alejandro R. Mosteo <alejandro@mosteo.com>"]
maintainers-logins = ["mosteo"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["directory", "folder", "enumeration", "traversal", "softlink"]

[[depends-on]]
aaa = "~0.3"
c_strings = "^1.1"

# Old test
[[actions]]
type      = "test"
command   = ["alr", "run"]
directory = "example"

# Only in 3.0-dev onwards
# [test]
# runner = "alire"

[origin]
commit = "6772b1deccfec2cba08cef582af89f70119052b7"
url = "git+https://github.com/mosteo/den"

