name = "zbmcompile"
description = "Message compiler for ZanyBlue Ada Localization"
version = "1.4.0"

authors = ["Michael Rohan"]
maintainers = ["Pascal Pignard <blady.net@orange.fr>"]
maintainers-logins = ["Blady-Com"]
licenses = "custom-zanyblue"
website = "https://sourceforge.net/projects/zanyblue"
tags = ["localization", "l10n", "international", "i18n"]

project-files = ["zbmcompile.gpr"]
executables = ["zbmcompile"]

# Release is broken but kept for reference
available = false

[[depends-on]]
zblib = "1.4.0"


[origin]
commit = "54c3421bda53d8c60b963448622318e724c55e5b"
subdir = "./src/zbmcompile/"
url = "git+https://github.com/Blady-Com/zanyblue.git"

