# Please read the TESTING file before modifying this file

# When the same index version is used by various stable and devel `alr`
# versions, we want to make sure all of them understand the index properly.

name: Build Crate (alr dev)
# Build the crate with a native toolchain from Alire

env:
  PACMAN: C:\Users\runneradmin\AppData\Local\alire\cache\msys64\usr\bin\pacman

on:
  pull_request:
    paths:
      - 'index/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:

  build:
    name: ${{ matrix.os }}
    env:
      JOB_NAME: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel    # amd64
          - macos-latest      # arm64
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest

    steps:
    - name: Check out repos
      uses: ./.github/actions/checkout-repos

    - name: Set up devel `alr`
      uses: alire-project/setup-alire@v5
      with:
        branch: 'master'

    - name: Install tar from msys2 (Windows) # Git tar in Actions VM does not seem to work
      if: matrix.os == 'windows-latest'
      run: ${{env.PACMAN}} --noconfirm -S tar

    - name: Test crate
      run: ${{env.CHECKS_REPO}}/scripts/gh-build-crate.sh
      shell: bash
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to apply labels/comment
