# Please read the TESTING file before modifying this file

# Specific workflow for MacPorts, as we need to disable Brew for this to work
# so it's difficult to use the other standard workflows.

name: Build Crate (MacPorts)
# Build the crate with a native toolchain from Alire

on:
  pull_request:
    paths:
      - 'index/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:

  build:
    name: ${{ matrix.os }}
    env:
      JOB_NAME: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15-intel  # amd64
          - macos-latest    # arm64

    steps:
    - name: Check out repos
      uses: ./.github/actions/checkout-repos

    - name: Set up `alr`
      uses: ./.github/actions/setup-alr

    - name: Disable Homebrew
      run: rm -f $(which brew)
      shell: bash

    - name: Install Ports
      uses: melusina-org/setup-macports@v1

    - name: Prefer Quartz to X11 for MacPorts
      shell: bash
      run: echo '-x11 +no_x11 +quartz' >> /opt/local/etc/macports/variants.conf

    - name: Test crate
      run: ${{env.CHECKS_REPO}}/scripts/gh-build-crate.sh
      shell: bash
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to apply labels/comment
