name: Check With Script

on:
  workflow_call:
    inputs:
      script:
        description: Script filename under alire-index-checks/scripts/
        required: true
        type: string
      script_arg:
        description: Single argument passed to the script
        required: true
        type: string
      setup_alr:
        description: Whether to install alr before running the script
        required: false
        type: boolean
        default: false

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repos
      uses: ./.github/actions/checkout-repos

    - name: Set up `alr`
      if: inputs.setup_alr
      uses: ./.github/actions/setup-alr

    - name: Run check
      run: >
        ${{env.CHECKS_REPO}}/scripts/${{inputs.script}}
        "$SCRIPT_ARG"
      shell: bash
      env:
        SCRIPT_ARG: ${{inputs.script_arg}}
