name: Check Index

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4

    - name: Set up `alr`
      uses: ./.github/actions/setup-alr

    - name: List current index
      run: alr index --list

    - name: Add local index
      run: alr index --add=. --name=local_index

    # Check index contents for unknown config variables
    - name: Check index
      run: alr index --check

    - name: Update index
      run: alr index --update-all

    - name: List crates
      run: alr search --crates
