# Please read the TESTING file before modifying this file

# Show differences between the submitted manifest and the previous
# release of the same crate, to enable easier catching of problems

name: Diff release

on:
  pull_request:
    paths:
      - 'index/**.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  DIFF:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repos
      uses: ./.github/actions/checkout-repos

    - name: Set up `alr`
      uses: ./.github/actions/setup-alr
      with:
        toolchain: --disable-assistant # No compiler needed

    - name: <<DIFF RELEASES>>
      run: ${{env.CHECKS_REPO}}/scripts/diff-release.sh || true # No deal breaker if failed
      shell: bash
