name = "espidf_wifi"
version = "0.1.0"
website = "https://github.com/godunko/espidf_wifi"
description = "Ada/ESP-IDF: Wi-Fi driver bindings"
long-description = """
Ada bindings for the ESP-IDF Wi-Fi driver (`esp_wifi`).

Covers:
- driver initialization, start/stop, connect/disconnect;
- mode selection (station, access point) and configuration storage;
- station and access point configuration (SSID, password, authentication mode, PMF);
- creation of default network interfaces for station and access point.
"""

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "esp", "esp32", "espidf", "wifi"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
espidf_netif = "^0.1.0"

[origin]
commit = "bf7178396359544708ce7fdad4e481addbc384b8"
url = "git+https://github.com/godunko/espidf_wifi.git"

